name: helium_mobile
description: "Helium is a smart student planner that lets organizes your classes, assignments, and grades into one color-coordinated calendar for academic success."

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  dio: ^5.4.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  file_picker: ^10.3.7
  share_plus: ^7.2.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1
  intl: ^0.20.1
  easy_stepper: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences_platform_interface: ^2.4.1
  firebase_core_platform_interface: ^6.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/