name: heliumapp
description: "Helium is a smart student planner that lets organizes your classes, assignments, and grades into one color-coordinated calendar for academic success."

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  logging: ^1.3.0
  sentry_flutter: ^9.10.0
  meta: ^1.17.0
  collection: ^1.19.0
  google_fonts: ^6.3.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.4.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.0
  device_info_plus: ^12.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.0
  timezone: ^0.10.0
  flutter_timezone: ^5.0.0
  intl: ^0.20.0
  flutter_local_notifications: ^18.0.0
  syncfusion_flutter_core: ^32.1.0
  syncfusion_flutter_calendar: ^32.1.0
  html_editor_enhanced: ^2.7.0
  flutter_html: ^3.0.0
  easy_stepper: ^1.0.0
  flutter_colorpicker: ^1.1.0
  file_picker: ^10.3.0
  url_launcher: ^6.3.0
  share_plus: ^12.0.0
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.0
  firebase_core_platform_interface: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/